const STORAGE_KEY = "jerrychuDrawBoardGithubV3";
const defaultSettings = {
  title:"제리츄 뽑기판", subtitle:"오늘의 행운을 뽑아보세요!", total:100, columns:10, loseText:"아쉽습니다!",
  prizes:[{rank:"1등",prize:"최고 상품",count:1,color:"#72beff"},{rank:"2등",prize:"행운 상품",count:3,color:"#9f8fff"},{rank:"3등",prize:"소소한 상품",count:6,color:"#ff88bf"}],
  integration:{enabled:false,execUrl:"",token:"",pollSeconds:5,bjId:"",maxDraws:100,kinds:{BALLOON_GIFTED:true,CHALLENGE_MISSION_GIFTED:true,BATTLE_MISSION_GIFTED:true},ruleMode:"ratio",ratio:{balloons:500,draws:1},ranges:[{min:500,max:999,draws:1},{min:1000,max:1999,draws:3},{min:2000,max:null,draws:7}],exacts:[{count:500,draws:1},{count:1000,draws:3},{count:2000,draws:7}]}
};
let state=loadState(); let pendingIndex=null; let pollTimer=null; let syncing=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function newState(){return{settings:structuredClone(defaultSettings),board:[],history:[],queue:[],importedEventIds:[]}}
function normalizeState(saved){const base=newState();return{settings:{...base.settings,...(saved.settings||{}),integration:{...base.settings.integration,...(saved.settings?.integration||{}),kinds:{...base.settings.integration.kinds,...(saved.settings?.integration?.kinds||{})},ratio:{...base.settings.integration.ratio,...(saved.settings?.integration?.ratio||{})},ranges:saved.settings?.integration?.ranges||base.settings.integration.ranges,exacts:saved.settings?.integration?.exacts||base.settings.integration.exacts}},board:Array.isArray(saved.board)?saved.board:[],history:Array.isArray(saved.history)?saved.history:[],queue:Array.isArray(saved.queue)?saved.queue:[],importedEventIds:Array.isArray(saved.importedEventIds)?saved.importedEventIds:[]}}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved?normalizeState(saved):newState()}catch{return newState()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function formatNumber(n){return String(n).padStart(Math.max(3,String(state.settings.total).length),"0")}
function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[c[i],c[j]]=[c[j],c[i]]}return c}
function currentTarget(){return state.queue.find(q=>q.remaining>0)||null}
function buildBoard(){const s=state.settings,items=[];s.prizes.forEach((p,pi)=>{for(let i=0;i<Number(p.count);i++)items.push({type:"win",prizeIndex:pi,rank:p.rank,prize:p.prize,color:p.color,opened:false,openedAt:null,participant:""})});for(let i=0;i<s.total-items.length;i++)items.push({type:"lose",rank:"꽝",prize:s.loseText,color:"#9ba7b8",opened:false,openedAt:null,participant:""});state.board=shuffle(items);state.history=[];saveState();renderAll()}
function renderAll(){renderHeader();renderPrizeList();renderBoard();renderHistory();renderQueue();renderSyncStatus()}
function renderHeader(){const total=state.board.length||Number(state.settings.total)||0,opened=state.board.filter(x=>x.opened).length,remaining=state.board.length?total-opened:0,wins=state.board.filter(x=>x.type==="win"&&!x.opened).length,progress=total?Math.round(opened/total*100):0;$("#displayTitle").textContent=state.settings.title;$("#displaySubtitle").textContent=state.settings.subtitle;$("#totalCount").textContent=total;$("#remainingCount").textContent=remaining;$("#winningRemaining").textContent=wins;$("#progressText").textContent=`${progress}%`;$("#progressBar").style.width=`${progress}%`;document.title=state.settings.title}
function renderPrizeList(){const list=$("#prizeList");list.innerHTML="";state.settings.prizes.forEach((p,i)=>{const total=Number(p.count)||0,opened=state.board.filter(x=>x.opened&&x.type==="win"&&x.prizeIndex===i).length,remaining=state.board.length?Math.max(0,total-opened):total;const el=document.createElement("div");el.className="prize-item";el.innerHTML=`<div class="prize-rank" style="--rank-color:${esc(p.color)}">${esc(p.rank)}</div><div class="prize-info"><strong>${esc(p.prize)}</strong><span>총 ${total}개</span></div><div class="prize-count">${remaining}개</div>`;list.appendChild(el)});const wt=state.settings.prizes.reduce((a,p)=>a+(Number(p.count)||0),0),lt=Math.max(0,state.settings.total-wt),lo=state.board.filter(x=>x.opened&&x.type==="lose").length,lr=state.board.length?Math.max(0,lt-lo):lt;list.insertAdjacentHTML("beforeend",`<div class="prize-item lose-summary"><div class="prize-rank" style="--rank-color:#9ba7b8">꽝</div><div class="prize-info"><strong>${esc(state.settings.loseText)}</strong><span>나머지 칸 자동 배치</span></div><div class="prize-count">${lr}개</div></div>`)}
function renderBoard(){const b=$("#drawBoard"),e=$("#boardEmpty");b.innerHTML="";if(!state.board.length){b.classList.add("hidden");e.classList.remove("hidden");return}b.classList.remove("hidden");e.classList.add("hidden");b.style.setProperty("--board-columns",state.settings.columns);state.board.forEach((item,i)=>{const btn=document.createElement("button");btn.className="draw-tile";if(item.opened){btn.classList.add("opened");btn.disabled=true;btn.style.setProperty("--tile-color",item.color||"#72beff");if(item.type==="lose")btn.classList.add("lose");btn.innerHTML=`<span class="tile-number">${item.type==="win"?`${esc(item.rank)}<br>${esc(item.prize)}`:esc(item.prize)}</span>`}else{btn.innerHTML=`<span class="tile-number">${formatNumber(i+1)}</span>`;btn.addEventListener("click",()=>openConfirm(i))}b.appendChild(btn)})}
function renderHistory(){const h=$("#recentHistory");if(!state.history.length){h.innerHTML=`<div class="empty-state">아직 뽑기 기록이 없어요.</div>`;return}h.innerHTML=state.history.slice().reverse().slice(0,20).map(x=>`<div class="history-item"><strong>${esc(x.participant)} · ${esc(x.result)}</strong><span>${esc(x.number)}번 · ${esc(x.time)}</span></div>`).join("")}
function renderQueue(){state.queue=state.queue.filter(q=>q.remaining>0);const cur=currentTarget(),card=$("#currentTargetCard"),actions=$("#currentTargetActions"),list=$("#drawQueueList");$("#queueCountBadge").textContent=`${state.queue.length}명`;if(cur){card.classList.remove("empty-target");card.innerHTML=`<div class="target-avatar"><img src="assets/mascot-character.png" alt="캐릭터"></div><div class="target-info"><span>${cur.source==="soop"?`별풍선 ${Number(cur.balloonCount||0).toLocaleString()}개`:"수동 등록"}</span><strong>${esc(cur.nickname)} · 남은 ${cur.remaining}회</strong><small>${esc(cur.memo||cur.kindLabel||"번호를 선택하면 자동으로 1회 차감됩니다.")}</small></div>`;actions.classList.remove("hidden");$("#participantName").value=cur.nickname}else{card.classList.add("empty-target");card.innerHTML=`<div class="target-avatar"><img src="assets/mascot-character.png" alt="캐릭터"></div><div class="target-info"><span>대기 중</span><strong>등록된 뽑기 대상이 없습니다.</strong><small>직접 이름을 입력하거나 SOOP 연동으로 불러오세요.</small></div>`;actions.classList.add("hidden")}
if(!state.queue.length){list.innerHTML=`<div class="empty-state">대기 중인 후원이 없습니다.</div>`}else list.innerHTML=state.queue.map((q,i)=>`<div class="queue-item ${i===0?"active":""}"><div class="queue-index">${i+1}</div><div class="queue-name"><strong>${esc(q.nickname)}</strong><span>${q.source==="soop"?`${Number(q.balloonCount||0).toLocaleString()}개 · ${esc(q.kindLabel||"")}`:esc(q.memo||"수동 등록")}</span></div><div class="queue-draws">${q.remaining}회</div></div>`).join("");saveState()}
function openConfirm(i){if(!state.board[i]||state.board[i].opened)return;pendingIndex=i;$("#confirmNumber").textContent=formatNumber(i+1);const cur=currentTarget(),name=cur?.nickname||$("#participantName").value.trim()||"이름 없음";$("#confirmParticipant").textContent=`주인공: ${name}${cur?` · 남은 ${cur.remaining}회`:""}`;openModal("confirmModal")}
function performDraw(){if(pendingIndex===null)return;const item=state.board[pendingIndex];if(!item||item.opened){closeModal("confirmModal");return}const cur=currentTarget(),name=cur?.nickname||$("#participantName").value.trim()||"이름 없음";item.opened=true;item.openedAt=new Date().toISOString();item.participant=name;const time=new Intl.DateTimeFormat("ko-KR",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date());state.history.push({number:formatNumber(pendingIndex+1),participant:name,result:item.type==="win"?`${item.rank} · ${item.prize}`:item.prize,type:item.type,time});if(cur){cur.remaining=Math.max(0,cur.remaining-1);cur.used=(cur.used||0)+1}saveState();closeModal("confirmModal");showResult(item,pendingIndex,name);pendingIndex=null;renderAll()}
function showResult(item,i,name){const c=$("#resultModalCard");c.classList.toggle("lose-result",item.type==="lose");if(item.type==="win"){$("#resultEmoji").textContent=item.rank==="1등"?"🎉":"✨";$("#resultRank").textContent=item.rank;$("#resultRank").style.background=item.color||"#9f8fff";$("#resultPrize").textContent=item.prize;$("#resultMessage").textContent=item.rank==="1등"?"대박입니다!":"축하합니다!"}else{$("#resultEmoji").textContent="💫";$("#resultRank").textContent="꽝";$("#resultRank").style.background="#9ba7b8";$("#resultPrize").textContent=item.prize;$("#resultMessage").textContent="다음 기회에는 꼭 당첨될 거예요!"}$("#resultMeta").textContent=`${name} · ${formatNumber(i+1)}번`;openModal("resultModal")}
function addQueueEntry({nickname,draws,source="manual",balloonCount=0,eventId="",kind="MANUAL",memo=""}){draws=Math.max(0,Math.floor(Number(draws)||0));if(!nickname||draws<1)return false;if(eventId&&(state.importedEventIds.includes(eventId)||state.queue.some(q=>q.eventId===eventId)))return false;state.queue.push({id:crypto.randomUUID(),nickname,remaining:draws,total:draws,used:0,source,balloonCount,eventId,kind,kindLabel:kindToLabel(kind),memo,createdAt:new Date().toISOString()});if(eventId){state.importedEventIds.push(eventId);state.importedEventIds=state.importedEventIds.slice(-3000)}saveState();renderQueue();return true}
function kindToLabel(k){return({BALLOON_GIFTED:"일반 후원",CHALLENGE_MISSION_GIFTED:"도전미션",BATTLE_MISSION_GIFTED:"배틀미션",MANUAL:"수동"})[k]||k||"후원"}
function calculateDraws(count,settings=state.settings.integration){count=Math.max(0,Number(count)||0);let n=0;if(settings.ruleMode==="ratio"){const b=Math.max(1,Number(settings.ratio.balloons)||1),d=Math.max(0,Number(settings.ratio.draws)||0);n=Math.floor(count/b)*d}else if(settings.ruleMode==="range"){const r=(settings.ranges||[]).find(x=>count>=Number(x.min||0)&&(x.max===null||x.max===""||count<=Number(x.max)));n=r?Number(r.draws)||0:0}else{const r=(settings.exacts||[]).find(x=>count===Number(x.count));n=r?Number(r.draws)||0:0}return Math.max(0,Math.min(Number(settings.maxDraws)||999,Math.floor(n)))}
function eventAllowed(ev,s=state.settings.integration){if(s.bjId&&String(ev.bjId||"").toLowerCase()!==String(s.bjId).toLowerCase())return false;return s.kinds?.[ev.kind]!==false}
function renderSyncStatus(mode){const s=state.settings.integration,d=$("#syncStatusDot"),t=$("#syncStatusText");d.className="status-dot ";if(!s.enabled){d.classList.add("off");t.textContent="사용 안 함";return}if(mode==="syncing"||syncing){d.classList.add("syncing");t.textContent="확인 중"}else if(mode==="error"){d.classList.add("error");t.textContent="연결 오류"}else{d.classList.add("ok");t.textContent="자동 확인 중"}}
function apiUrl(action,extra={}){const base=state.settings.integration.execUrl.trim();if(!base)return"";const u=new URL(base);u.searchParams.set("action",action);u.searchParams.set("token",state.settings.integration.token||"");Object.entries(extra).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,v)});u.searchParams.set("_",Date.now());return u.toString()}
async function fetchJson(url){const r=await fetch(url,{method:"GET",cache:"no-store",redirect:"follow"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const text=await r.text();try{return JSON.parse(text)}catch{throw new Error("JSON 응답이 아닙니다.")}}
async function testConnection(useDraft=true){const el=$("#connectionTestResult");try{if(useDraft){const draft=getDraftIntegration();if(!draft.execUrl)throw new Error("Apps Script 주소를 입력해 주세요.");const u=new URL(draft.execUrl);u.searchParams.set("action","drawPing");u.searchParams.set("token",draft.token||"");u.searchParams.set("bjId",draft.bjId||"");u.searchParams.set("_",Date.now());el.textContent="연결 확인 중...";el.className="connection-result";const data=await fetchJson(u.toString());if(!data.ok)throw new Error(data.message||"연결 실패")}else{const data=await fetchJson(apiUrl("drawPing"));if(!data.ok)throw new Error(data.message||"연결 실패")}el.textContent="Apps Script 연결 확인 완료";el.className="connection-result ok";return true}catch(e){el.textContent=`연결 실패: ${e.message}`;el.className="connection-result error";return false}}
async function syncGifts(){const s=state.settings.integration;if(syncing||!s.enabled||!s.execUrl)return;syncing=true;renderSyncStatus("syncing");try{const data=await fetchJson(apiUrl("drawEvents",{bjId:s.bjId||""}));if(!data.ok)throw new Error(data.message||"수신 실패");let added=0;for(const ev of (data.events||[])){if(!ev.eventId||state.importedEventIds.includes(String(ev.eventId)))continue;if(!eventAllowed(ev,s)){await acknowledgeEvent(ev.eventId,"ignored");state.importedEventIds.push(String(ev.eventId));continue}const draws=calculateDraws(ev.count,s);if(draws>0&&addQueueEntry({nickname:ev.nickname||ev.userId||"익명",draws,source:"soop",balloonCount:ev.count,eventId:String(ev.eventId),kind:ev.kind,memo:`${kindToLabel(ev.kind)} · 자동 지급 ${draws}회`}))added++;else state.importedEventIds.push(String(ev.eventId));await acknowledgeEvent(ev.eventId,draws>0?"queued":"no_draw")}state.importedEventIds=[...new Set(state.importedEventIds)].slice(-3000);saveState();renderAll();renderSyncStatus()}catch(e){console.error(e);renderSyncStatus("error")}finally{syncing=false}}
async function acknowledgeEvent(eventId,status){try{const d=await fetchJson(apiUrl("drawAck",{eventId,status}));return d.ok}catch{return false}}
function restartPolling(){clearInterval(pollTimer);pollTimer=null;if(state.settings.integration.enabled){const sec=Math.max(3,Number(state.settings.integration.pollSeconds)||5);pollTimer=setInterval(syncGifts,sec*1000);setTimeout(syncGifts,400)}}
function openModal(id){document.getElementById(id).classList.remove("hidden");document.body.style.overflow="hidden"}function closeModal(id){document.getElementById(id).classList.add("hidden");if($$(".modal-backdrop:not(.hidden)").length===0)document.body.style.overflow=""}
function renderSettings(){const s=state.settings,i=s.integration;$("#settingTitle").value=s.title;$("#settingSubtitle").value=s.subtitle;$("#settingTotal").value=s.total;$("#settingColumns").value=s.columns;$("#settingLoseText").value=s.loseText;renderPrizeEditor(s.prizes);$("#soopEnabled").checked=i.enabled;$("#soopExecUrl").value=i.execUrl;$("#soopToken").value=i.token;$("#soopPollSeconds").value=String(i.pollSeconds);$("#soopBjId").value=i.bjId;$("#soopMaxDraws").value=i.maxDraws;$("#kindBalloon").checked=i.kinds.BALLOON_GIFTED!==false;$("#kindChallenge").checked=i.kinds.CHALLENGE_MISSION_GIFTED!==false;$("#kindBattle").checked=i.kinds.BATTLE_MISSION_GIFTED!==false;const radio=$(`input[name="ruleMode"][value="${i.ruleMode}"]`);if(radio)radio.checked=true;$("#ratioBalloons").value=i.ratio.balloons;$("#ratioDraws").value=i.ratio.draws;renderRangeRules(i.ranges);renderExactRules(i.exacts);updateRulePanels();updateSettingsSummary();updateTestDrawResult()}
function renderPrizeEditor(prizes){const ed=$("#prizeEditor");ed.innerHTML="";prizes.forEach(p=>{const row=document.createElement("div");row.className="prize-edit-row";row.innerHTML=`<label><span>등수</span><input class="edit-rank" type="text" maxlength="12" value="${esc(p.rank)}"></label><label><span>상품명 / 당첨 문구</span><input class="edit-prize" type="text" maxlength="40" value="${esc(p.prize)}"></label><label><span>개수</span><input class="edit-count" type="number" min="0" max="300" value="${Number(p.count)||0}"></label><label><span>색상</span><input class="edit-color color-input" type="color" value="${esc(p.color||"#9f8fff")}"></label><div class="delete-cell"><button class="icon-btn delete-prize">×</button></div>`;ed.appendChild(row)});$$(".prize-editor input").forEach(x=>x.addEventListener("input",updateSettingsSummary));$$(".delete-prize").forEach(x=>x.addEventListener("click",e=>{e.currentTarget.closest(".prize-edit-row").remove();updateSettingsSummary()}))}
function getEditorPrizes(){return $$(".prize-edit-row").map(r=>({rank:r.querySelector(".edit-rank").value.trim()||"당첨",prize:r.querySelector(".edit-prize").value.trim()||"상품",count:Math.max(0,Number(r.querySelector(".edit-count").value)||0),color:r.querySelector(".edit-color").value||"#9f8fff"}))}
function renderRangeRules(rules){const e=$("#rangeRuleEditor");e.innerHTML="";(rules||[]).forEach(r=>e.insertAdjacentHTML("beforeend",`<div class="range-rule-row"><input class="range-min" type="number" min="0" value="${Number(r.min)||0}"><span>~</span><input class="range-max" type="number" min="0" placeholder="제한 없음" value="${r.max??""}"><span>→</span><input class="range-draws" type="number" min="0" value="${Number(r.draws)||0}"><button class="rule-delete">×</button></div>`));bindRuleDeletes()}
function renderExactRules(rules){const e=$("#exactRuleEditor");e.innerHTML="";(rules||[]).forEach(r=>e.insertAdjacentHTML("beforeend",`<div class="exact-rule-row"><input class="exact-count" type="number" min="0" value="${Number(r.count)||0}"><span>개 →</span><input class="exact-draws" type="number" min="0" value="${Number(r.draws)||0}"><button class="rule-delete">×</button></div>`));bindRuleDeletes()}
function bindRuleDeletes(){$$(".rule-delete").forEach(x=>x.onclick=e=>{e.currentTarget.parentElement.remove();updateTestDrawResult()});$$('.rule-editor input').forEach(x=>x.oninput=updateTestDrawResult)}
function getDraftIntegration(){const mode=$('input[name="ruleMode"]:checked')?.value||"ratio";return{enabled:$("#soopEnabled").checked,execUrl:$("#soopExecUrl").value.trim(),token:$("#soopToken").value.trim(),pollSeconds:Math.max(3,Number($("#soopPollSeconds").value)||5),bjId:$("#soopBjId").value.trim(),maxDraws:Math.max(1,Number($("#soopMaxDraws").value)||100),kinds:{BALLOON_GIFTED:$("#kindBalloon").checked,CHALLENGE_MISSION_GIFTED:$("#kindChallenge").checked,BATTLE_MISSION_GIFTED:$("#kindBattle").checked},ruleMode:mode,ratio:{balloons:Math.max(1,Number($("#ratioBalloons").value)||1),draws:Math.max(0,Number($("#ratioDraws").value)||0)},ranges:$$(".range-rule-row").map(r=>({min:Math.max(0,Number(r.querySelector(".range-min").value)||0),max:r.querySelector(".range-max").value===""?null:Math.max(0,Number(r.querySelector(".range-max").value)||0),draws:Math.max(0,Number(r.querySelector(".range-draws").value)||0)})),exacts:$$(".exact-rule-row").map(r=>({count:Math.max(0,Number(r.querySelector(".exact-count").value)||0),draws:Math.max(0,Number(r.querySelector(".exact-draws").value)||0)}))}}
function getDraftSettings(){return{title:$("#settingTitle").value.trim()||"제리츄 뽑기판",subtitle:$("#settingSubtitle").value.trim()||"오늘의 행운을 뽑아보세요!",total:Math.max(1,Math.min(300,Number($("#settingTotal").value)||100)),columns:Math.max(2,Math.min(20,Number($("#settingColumns").value)||10)),loseText:$("#settingLoseText").value.trim()||"아쉽습니다!",prizes:getEditorPrizes(),integration:getDraftIntegration()}}
function validateSettings(s){const w=s.prizes.reduce((a,p)=>a+p.count,0);if(!s.prizes.length)return"당첨 항목을 한 개 이상 추가해 주세요.";if(w>s.total)return`당첨 수량이 전체 칸 수보다 ${w-s.total}개 많습니다.`;if(s.integration.enabled&&!s.integration.execUrl)return"SOOP 연동을 사용할 경우 Apps Script 주소를 입력해 주세요.";return""}
function updateSettingsSummary(){const s=getDraftSettings(),w=s.prizes.reduce((a,p)=>a+p.count,0),err=validateSettings(s);$("#summaryTotal").textContent=s.total;$("#summaryWin").textContent=w;$("#summaryLose").textContent=Math.max(0,s.total-w);$("#settingError").textContent=err;$("#settingError").classList.toggle("hidden",!err);$("#generateBoardBtn").disabled=Boolean(err)}
function saveSettingsOnly(){const s=getDraftSettings(),err=validateSettings(s);if(err){updateSettingsSummary();return}state.settings=s;saveState();renderAll();restartPolling();closeModal("settingsModal")}
function generateFromSettings(){const s=getDraftSettings(),err=validateSettings(s);if(err){updateSettingsSummary();return}if(state.board.some(x=>x.opened)&&!confirm("새 뽑기판을 만들면 현재 진행 기록과 열린 칸이 모두 초기화됩니다. 계속할까요?"))return;state.settings=s;buildBoard();restartPolling();closeModal("settingsModal")}
function addPrizeRow(){const p=getEditorPrizes(),n=p.length+1,pal=["#72beff","#9f8fff","#ff88bf","#83e5f0","#ffc46b","#78d0a0"];p.push({rank:`${n}등`,prize:"새 상품",count:1,color:pal[(n-1)%pal.length]});renderPrizeEditor(p);updateSettingsSummary()}
function updateRulePanels(){const m=$('input[name="ruleMode"]:checked')?.value||"ratio";$("#ratioRulePanel").classList.toggle("hidden",m!=="ratio");$("#rangeRulePanel").classList.toggle("hidden",m!=="range");$("#exactRulePanel").classList.toggle("hidden",m!=="exact");updateTestDrawResult()}
function updateTestDrawResult(){try{$("#testDrawResult").textContent=`${calculateDraws($("#testBalloonCount").value,getDraftIntegration())}회`}catch{$("#testDrawResult").textContent="0회"}}
function renderPreview(){const g=$("#previewGrid");if(!state.board.length){g.innerHTML=`<div class="empty-state">생성된 뽑기판이 없습니다.</div>`;return}g.innerHTML=state.board.map((x,i)=>`<div class="preview-item ${x.type==="lose"?"lose-preview":""}" style="--preview-color:${esc(x.color||"#9f8fff")}"><b>${formatNumber(i+1)}번 ${x.opened?"· 공개됨":""}</b>${x.type==="win"?`${esc(x.rank)} · ${esc(x.prize)}`:esc(x.prize)}</div>`).join("")}
function exportCsv(){if(!state.board.length)return;const rows=[["번호","결과","상품/문구","공개 여부","참가자","공개 시각"]];state.board.forEach((x,i)=>rows.push([formatNumber(i+1),x.type==="win"?x.rank:"꽝",x.prize,x.opened?"공개":"미공개",x.participant||"",x.openedAt||""]));const csv="\uFEFF"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8;"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="제리츄_뽑기판_결과.csv";a.click();URL.revokeObjectURL(url)}
function resetProgress(){if(!state.board.length||!confirm("뽑기 결과 배치는 유지하고, 열린 칸과 기록만 초기화할까요?"))return;state.board=state.board.map(x=>({...x,opened:false,openedAt:null,participant:""}));state.history=[];saveState();renderAll()}
function clearHistory(){if(!confirm("최근 결과 기록만 지울까요? 열린 칸은 그대로 유지됩니다."))return;state.history=[];saveState();renderHistory()}
$("#confirmDrawBtn").onclick=performDraw;$("#settingsBtn").onclick=()=>{renderSettings();openModal("settingsModal")};$("#emptySettingsBtn").onclick=()=>{renderSettings();openModal("settingsModal")};$("#previewBtn").onclick=()=>{renderPreview();openModal("previewModal")};$("#resetProgressBtn").onclick=resetProgress;$("#clearHistoryBtn").onclick=clearHistory;$("#addPrizeBtn").onclick=addPrizeRow;$("#saveSettingsBtn").onclick=saveSettingsOnly;$("#generateBoardBtn").onclick=generateFromSettings;$("#exportCsvBtn").onclick=exportCsv;$("#syncNowBtn").onclick=syncGifts;$("#testConnectionBtn").onclick=()=>testConnection(true);
$("#manualQueueBtn").onclick=()=>openModal("manualQueueModal");$("#manualQueueAddBtn").onclick=()=>{const n=$("#manualNickname").value.trim(),d=$("#manualDraws").value,m=$("#manualMemo").value.trim();if(addQueueEntry({nickname:n,draws:d,memo:m})){closeModal("manualQueueModal");$("#manualNickname").value="";$("#manualDraws").value=1;$("#manualMemo").value=""}};
$("#targetMinusBtn").onclick=()=>{const c=currentTarget();if(c){c.remaining=Math.max(0,c.remaining-1);saveState();renderQueue()}};$("#targetPlusBtn").onclick=()=>{const c=currentTarget();if(c){c.remaining++;c.total++;saveState();renderQueue()}};$("#targetSkipBtn").onclick=()=>{const c=currentTarget();if(c){state.queue=state.queue.filter(x=>x.id!==c.id);state.queue.push(c);saveState();renderQueue()}};$("#targetRemoveBtn").onclick=()=>{const c=currentTarget();if(c&&confirm(`${c.nickname} 님을 대기열에서 삭제할까요?`)){state.queue=state.queue.filter(x=>x.id!==c.id);saveState();renderQueue()}};
$$(".settings-tab").forEach(t=>t.onclick=()=>{$$(".settings-tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");$$(".settings-tab-panel").forEach(x=>x.classList.add("hidden"));document.getElementById(t.dataset.tab).classList.remove("hidden")});
$$('input[name="ruleMode"]').forEach(x=>x.onchange=updateRulePanels);$("#addRangeRuleBtn").onclick=()=>{$("#rangeRuleEditor").insertAdjacentHTML("beforeend",`<div class="range-rule-row"><input class="range-min" type="number" min="0" value="0"><span>~</span><input class="range-max" type="number" min="0" placeholder="제한 없음"><span>→</span><input class="range-draws" type="number" min="0" value="1"><button class="rule-delete">×</button></div>`);bindRuleDeletes()};$("#addExactRuleBtn").onclick=()=>{$("#exactRuleEditor").insertAdjacentHTML("beforeend",`<div class="exact-rule-row"><input class="exact-count" type="number" min="0" value="500"><span>개 →</span><input class="exact-draws" type="number" min="0" value="1"><button class="rule-delete">×</button></div>`);bindRuleDeletes()};
$("#testBalloonCount").oninput=updateTestDrawResult;["ratioBalloons","ratioDraws","soopMaxDraws"].forEach(id=>$("#"+id).oninput=updateTestDrawResult);$("#testAddQueueBtn").onclick=()=>{const count=Number($("#testBalloonCount").value)||0,draws=calculateDraws(count,getDraftIntegration());if(draws>0)addQueueEntry({nickname:"연동 테스트",draws,source:"manual",balloonCount:count,memo:`별풍선 ${count.toLocaleString()}개 계산 테스트`})};
["settingTotal","settingColumns","settingLoseText","settingTitle","settingSubtitle","soopEnabled","soopExecUrl"].forEach(id=>$("#"+id).addEventListener("input",updateSettingsSummary));$$("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$(".modal-backdrop").forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});document.addEventListener("keydown",e=>{if(e.key==="Escape")$$(".modal-backdrop:not(.hidden)").forEach(m=>closeModal(m.id))});
renderAll();restartPolling();
